-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.car_brands
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    is_other boolean NOT NULL DEFAULT false,
    CONSTRAINT car_brands_pkey PRIMARY KEY (id),
    CONSTRAINT car_brands_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.car_models
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    brand_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_other boolean NOT NULL DEFAULT false,
    CONSTRAINT car_models_pkey PRIMARY KEY (id),
    CONSTRAINT car_models_brand_id_name_key UNIQUE (brand_id, name)
);

CREATE TABLE IF NOT EXISTS public.gallery
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default" NOT NULL,
    category text COLLATE pg_catalog."default",
    uploaded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT gallery_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.requests
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    service_id integer NOT NULL,
    car_model text COLLATE pg_catalog."default" NOT NULL,
    car_year integer,
    car_number text COLLATE pg_catalog."default",
    problem_description text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    appointment_date timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    car_brand_id integer,
    car_model_id integer,
    custom_brand text COLLATE pg_catalog."default",
    custom_model text COLLATE pg_catalog."default",
    CONSTRAINT requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    request_id integer,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    is_approved boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    name text COLLATE pg_catalog."default" NOT NULL,
    applied_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.services
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10, 2) NOT NULL,
    duration integer,
    category text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    phone text COLLATE pg_catalog."default",
    role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'client'::text,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password_reset_token text COLLATE pg_catalog."default",
    password_reset_expires timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.car_models
    ADD CONSTRAINT car_models_brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES public.car_brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_car_models_brand_id
    ON public.car_models(brand_id);


ALTER TABLE IF EXISTS public.requests
    ADD CONSTRAINT requests_car_brand_id_fkey FOREIGN KEY (car_brand_id)
    REFERENCES public.car_brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_requests_car_brand_id
    ON public.requests(car_brand_id);


ALTER TABLE IF EXISTS public.requests
    ADD CONSTRAINT requests_car_model_id_fkey FOREIGN KEY (car_model_id)
    REFERENCES public.car_models (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.requests
    ADD CONSTRAINT requests_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.requests
    ADD CONSTRAINT requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;