-- Справочники марок и моделей автомобилей
CREATE TABLE IF NOT EXISTS car_brands (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  is_other BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS car_models (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  brand_id INTEGER NOT NULL REFERENCES car_brands(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_other BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (brand_id, name)
);

ALTER TABLE requests
  ADD COLUMN IF NOT EXISTS car_brand_id INTEGER REFERENCES car_brands(id),
  ADD COLUMN IF NOT EXISTS car_model_id INTEGER REFERENCES car_models(id),
  ADD COLUMN IF NOT EXISTS custom_brand TEXT,
  ADD COLUMN IF NOT EXISTS custom_model TEXT;

CREATE INDEX IF NOT EXISTS idx_requests_car_brand_id ON requests (car_brand_id);
CREATE INDEX IF NOT EXISTS idx_car_models_brand_id ON car_models (brand_id);

-- Seed: марки (idempotent)
INSERT INTO car_brands (name, is_other) VALUES
  ('Lada', FALSE),
  ('Toyota', FALSE),
  ('Kia', FALSE),
  ('Hyundai', FALSE),
  ('Volkswagen', FALSE),
  ('BMW', FALSE),
  ('Mercedes-Benz', FALSE),
  ('Audi', FALSE),
  ('Renault', FALSE),
  ('Skoda', FALSE),
  ('Nissan', FALSE),
  ('Mazda', FALSE),
  ('Ford', FALSE),
  ('Chevrolet', FALSE),
  ('Haval', FALSE),
  ('Chery', FALSE),
  ('Geely', FALSE),
  ('Другое', TRUE)
ON CONFLICT (name) DO NOTHING;

-- Seed: модели по маркам
INSERT INTO car_models (brand_id, name, is_other)
SELECT b.id, m.name, m.is_other
FROM (VALUES
  ('Lada', 'Vesta', FALSE),
  ('Lada', 'Granta', FALSE),
  ('Lada', 'Largus', FALSE),
  ('Lada', 'Niva Travel', FALSE),
  ('Lada', 'Niva Legend', FALSE),
  ('Lada', 'XRAY', FALSE),
  ('Lada', 'Другое', TRUE),
  ('Toyota', 'Camry', FALSE),
  ('Toyota', 'Corolla', FALSE),
  ('Toyota', 'RAV4', FALSE),
  ('Toyota', 'Land Cruiser', FALSE),
  ('Toyota', 'Highlander', FALSE),
  ('Toyota', 'Yaris', FALSE),
  ('Toyota', 'Другое', TRUE),
  ('Kia', 'Rio', FALSE),
  ('Kia', 'Ceed', FALSE),
  ('Kia', 'Sportage', FALSE),
  ('Kia', 'Sorento', FALSE),
  ('Kia', 'K5', FALSE),
  ('Kia', 'Cerato', FALSE),
  ('Kia', 'Другое', TRUE),
  ('Hyundai', 'Solaris', FALSE),
  ('Hyundai', 'Creta', FALSE),
  ('Hyundai', 'Tucson', FALSE),
  ('Hyundai', 'Santa Fe', FALSE),
  ('Hyundai', 'Elantra', FALSE),
  ('Hyundai', 'Sonata', FALSE),
  ('Hyundai', 'Другое', TRUE),
  ('Volkswagen', 'Polo', FALSE),
  ('Volkswagen', 'Golf', FALSE),
  ('Volkswagen', 'Tiguan', FALSE),
  ('Volkswagen', 'Passat', FALSE),
  ('Volkswagen', 'Touareg', FALSE),
  ('Volkswagen', 'Другое', TRUE),
  ('BMW', '3 Series', FALSE),
  ('BMW', '5 Series', FALSE),
  ('BMW', 'X3', FALSE),
  ('BMW', 'X5', FALSE),
  ('BMW', 'X7', FALSE),
  ('BMW', 'Другое', TRUE),
  ('Mercedes-Benz', 'C-Class', FALSE),
  ('Mercedes-Benz', 'E-Class', FALSE),
  ('Mercedes-Benz', 'GLC', FALSE),
  ('Mercedes-Benz', 'GLE', FALSE),
  ('Mercedes-Benz', 'S-Class', FALSE),
  ('Mercedes-Benz', 'Другое', TRUE),
  ('Audi', 'A3', FALSE),
  ('Audi', 'A4', FALSE),
  ('Audi', 'A6', FALSE),
  ('Audi', 'Q5', FALSE),
  ('Audi', 'Q7', FALSE),
  ('Audi', 'Другое', TRUE),
  ('Renault', 'Logan', FALSE),
  ('Renault', 'Sandero', FALSE),
  ('Renault', 'Duster', FALSE),
  ('Renault', 'Arkana', FALSE),
  ('Renault', 'Kaptur', FALSE),
  ('Renault', 'Другое', TRUE),
  ('Skoda', 'Octavia', FALSE),
  ('Skoda', 'Rapid', FALSE),
  ('Skoda', 'Kodiaq', FALSE),
  ('Skoda', 'Karoq', FALSE),
  ('Skoda', 'Superb', FALSE),
  ('Skoda', 'Другое', TRUE),
  ('Nissan', 'Qashqai', FALSE),
  ('Nissan', 'X-Trail', FALSE),
  ('Nissan', 'Almera', FALSE),
  ('Nissan', 'Terrano', FALSE),
  ('Nissan', 'Murano', FALSE),
  ('Nissan', 'Другое', TRUE),
  ('Mazda', '3', FALSE),
  ('Mazda', '6', FALSE),
  ('Mazda', 'CX-5', FALSE),
  ('Mazda', 'CX-9', FALSE),
  ('Mazda', 'Другое', TRUE),
  ('Ford', 'Focus', FALSE),
  ('Ford', 'Mondeo', FALSE),
  ('Ford', 'Kuga', FALSE),
  ('Ford', 'Explorer', FALSE),
  ('Ford', 'Другое', TRUE),
  ('Chevrolet', 'Niva', FALSE),
  ('Chevrolet', 'Cruze', FALSE),
  ('Chevrolet', 'Aveo', FALSE),
  ('Chevrolet', 'Captiva', FALSE),
  ('Chevrolet', 'Другое', TRUE),
  ('Haval', 'Jolion', FALSE),
  ('Haval', 'F7', FALSE),
  ('Haval', 'Dargo', FALSE),
  ('Haval', 'H6', FALSE),
  ('Haval', 'Другое', TRUE),
  ('Chery', 'Tiggo 4', FALSE),
  ('Chery', 'Tiggo 7 Pro', FALSE),
  ('Chery', 'Tiggo 8 Pro', FALSE),
  ('Chery', 'Arrizo 8', FALSE),
  ('Chery', 'Другое', TRUE),
  ('Geely', 'Coolray', FALSE),
  ('Geely', 'Atlas Pro', FALSE),
  ('Geely', 'Monjaro', FALSE),
  ('Geely', 'Emgrand', FALSE),
  ('Geely', 'Другое', TRUE),
  ('Другое', 'Другое', TRUE)
) AS m(brand_name, name, is_other)
JOIN car_brands b ON b.name = m.brand_name
ON CONFLICT (brand_id, name) DO NOTHING;
